
version: "3.7"
services:
  react:
    build: ./digital-card-front
    container_name: react
    ports:
      - 3000:3000
    env_file:
      - ./digital-card-front/.env
    volumes:
      - build_react:/var/www/html
    depends_on:
      - node
    
  node:
    build: ./digital-card-back
    container_name: node
    ports:
      - 4000:4000
    env_file:
      - ./digital-card-back/.env
    volumes:
      - ./digital-card-back:/usr/src
      - /usr/src/node_modules
    command: "npm run start"
   
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 5000:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react
volumes:
  build_react:
